version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:4000
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - SCRAPER_URL=http://scraper:5000
    depends_on:
      - scraper

  scraper:
    build: ./scraper
    ports:
      - "5000:5000"
    cap_add:
      - SYS_ADMIN
    environment:
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
